name: make a mesa
on:
   workflow_dispatch:

   push:
    branches: [ "Panfrost-G610" ]
jobs:
  job-ubuntu:
    runs-on: ubuntu-22-04
    steps:
      - name: "Environment Preparation"
        run: |
           sudo apt update
           sudo apt install -y python3 python3-pip cmake wget git p7zip build-essential pkg-config xmlto fop xsltproc llvm autoconf libxml-parser-perl bison flex glslang-tools
           pip3 install mako meson ninja docutils StrEnum
           sudo ln -sf ~/.local/bin/meson /usr/bin/meson
    
      - name: "Clone MiceWine-RootFS-Generator"
        run: |
           git clone https://github.com/KreitinnSoftware/MiceWine-RootFS-Generator

      - name: "Download Latest Release Rat Packages"
        run: |
           cd MiceWine-RootFS-Generator
           curl -LO# https://github.com/KreitinnSoftware/MiceWine-RootFS-Generator/releases/download/$(curl -s https://api.github.com/repos/KreitinnSoftware/MiceWine-RootFS-Generator/releases | grep tag_name -m 1 | cut -d ":" -f 2 | sed "s/\"//g" | sed "s/,//g" | sed "s/ //g")/MiceWine-Packages.zip || true
           unzip -o MiceWine-Packages.zip -d built-pkgs || true

      - name: "Create Mesa-Panfork Package on MiceWine-RootFS-Generator"
        run: |
           cd MiceWine-RootFS-Generator
           mkdir -p packages/mesa-panfork
           echo PKG_VER=23.0.0-devel > packages/mesa-panfork/build.sh
           echo PKG_CATEGORY=OpenGLDriver >> packages/mesa-panfork/build.sh
           echo PKG_PRETTY_NAME="Mesa Panfork Driver" >> packages/mesa-panfork/build.sh
           echo BLACKLIST_ARCHITECTURE=x86_64 >> packages/mesa-panfork/build.sh
           echo GIT_URL=https://github.com/KreitinnSoftware/mesa-Panfork >> packages/mesa-panfork/build.sh
           echo LDFLAGS="-L$PREFIX/lib -landroid-shmem -Wl,--undefined-version" >> packages/mesa-panfork/build.sh
           echo MESON_ARGS="-Dgallium-drivers=swrast,panfrost -Dvulkan-drivers= -Dglvnd=disabled -Dplatforms=x11 -Dxmlconfig=disabled -Dllvm=disabled -Dopengl=true -Degl=disabled -Dzstd=enabled" >> packages/mesa-panfork/build.sh

           echo mesa-panfork >> packages/index

      - name: "Compile Mesa Panfork"
        run: |
           cd MiceWine-RootFS-Generator
           ./build-all.sh aarch64
           cd logs
           7z a /home/runner/Mesa-Panfork-Logs.zip

      - name: "Save Mesa Panfork"
        run: |
           cd MiceWine-RootFS-Generator
           cp -rf built-pkgs/mesa-panfork* /home/runner/Mesa-Panfork.rat

      - name: "Create Release"
        uses: softprops/action-gh-release@v2
        with:
          name: "Mesa Panfork"
          tag_name: mesa-panfork
          prerelease: true
          files: |
             /home/runner/Mesa-Panfork-Logs.zip
             /home/runner/Mesa-Panfork.rat
